// <auto-generated />
namespace MisOfertas.CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nueva : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nueva));
        
        string IMigrationMetadata.Id
        {
            get { return "201910082331583_nueva"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
